behaviors:
  GoalToTetris:
    trainer_type: ppo
    max_steps: 500000
    time_horizon: 128
    summary_freq: 10000
    network_settings:
      hidden_units: 128
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
